"""
Django settings for mental_fitness_coach project.

Generated by Django 5.x
For more information on this file, see:
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see:
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# ==================== BUILD PATHS ====================

# Base directory of the project
BASE_DIR = Path(__file__).resolve().parent.parent


# ==================== SECURITY SETTINGS ====================

# SECURITY WARNING: keep the secret key used in production secret!
# Generate a new key using: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'
SECRET_KEY = 'django-insecure-your-secret-key-here-change-in-production'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Allowed hosts - add your domain in production
ALLOWED_HOSTS = []


# ==================== APPLICATION DEFINITION ====================

INSTALLED_APPS = [
    # Django built-in apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Your custom users app
    'users',
    'data'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mental_fitness_coach.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mental_fitness_coach.wsgi.application'


# ==================== DATABASE ====================

# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ==================== PASSWORD VALIDATION ====================

# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ==================== INTERNATIONALIZATION ====================

# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ==================== STATIC FILES (CSS, JavaScript, Images) ====================

# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'


# ==================== MEDIA FILES ====================

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'


# ==================== DEFAULT PRIMARY KEY FIELD TYPE ====================

# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==================== CUSTOM USER MODEL ====================

# Tells Django to use your custom User model from the users app



# ==================== AUTHENTICATION BACKENDS ====================
AUTH_USER_MODEL = 'users.User'
LOGIN_REDIRECT_URL = '/health/add/'
LOGIN_URL = '/login/'
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]


# ==================== LOGIN / LOGOUT REDIRECTS ====================

# Where to redirect after login
LOGIN_REDIRECT_URL = '/users/dashboard/'

# Where to redirect if login is required but user is not logged in
LOGIN_URL = '/users/login/'

# Where to redirect after logout
LOGOUT_REDIRECT_URL = '/users/login/'


# ==================== SESSION SETTINGS (Keep Me Logged In) ====================

# Default session cookie age: 2 weeks (1209600 seconds)
SESSION_COOKIE_AGE = 1209600

# Refresh session expiry on every request (extends "Keep me logged in")
SESSION_SAVE_EVERY_REQUEST = True

# Allow persistent sessions (don't expire when browser closes)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Prevent JavaScript access to session cookie
SESSION_COOKIE_HTTPONLY = True

# Use secure cookies in production (HTTPS only)
# SESSION_COOKIE_SECURE = True


# ==================== CSRF PROTECTION ====================

CSRF_COOKIE_HTTPONLY = True

# Use secure CSRF cookies in production
# CSRF_COOKIE_SECURE = True


# ==================== EMAIL CONFIGURATION ====================

# For development: emails are printed to the console
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For production (example with Gmail SMTP):
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'  # Use app-specific password, not your Gmail password
# DEFAULT_FROM_EMAIL = 'Mental Fitness Coach <noreply@yourdomain.com>'

# Site URL used in email templates (change to your production domain)
SITE_URL = 'http://127.0.0.1:8000'


# ==================== MESSAGE SETTINGS ====================

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'error',
}


# ==================== SECURITY HEADERS (Enable in Production) ====================

# Enable browser XSS filter
# SECURE_BROWSER_XSS_FILTER = True

# Prevent MIME type sniffing
# SECURE_CONTENT_TYPE_NOSNIFF = True

# Prevent clickjacking
# X_FRAME_OPTIONS = 'DENY'

# Redirect all HTTP to HTTPS
# SECURE_SSL_REDIRECT = True

# HSTS (HTTP Strict Transport Security)
# SECURE_HSTS_SECONDS = 31536000  # 1 year
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True


# ==================== LOGGING ====================

# ==================== LOGGING ====================

LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(parents=True, exist_ok=True)


# Create logs directory if it doesn't exist

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR / 'django_error.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}