# Generated by Django 6.0.6 on 2026-07-16 13:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sleep_hours', models.DecimalField(decimal_places=1, help_text='Hours slept last night (0-24)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('sleep_quality', models.PositiveSmallIntegerField(help_text='Sleep quality rating: 1 (terrible) to 10 (excellent)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('bp_systolic', models.PositiveSmallIntegerField(help_text='Systolic BP (top number)', validators=[django.core.validators.MinValueValidator(70), django.core.validators.MaxValueValidator(200)])),
                ('bp_diastolic', models.PositiveSmallIntegerField(help_text='Diastolic BP (bottom number)', validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(130)])),
                ('anxiety_level', models.PositiveSmallIntegerField(help_text='Anxiety level: 1 (none) to 10 (severe)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('stress_level', models.PositiveSmallIntegerField(help_text='Stress level: 1 (none) to 10 (extreme)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('fatigue_level', models.PositiveSmallIntegerField(help_text='Fatigue level: 1 (energetic) to 10 (exhausted)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('mood_rating', models.PositiveSmallIntegerField(help_text='Overall mood: 1 (very low) to 10 (excellent)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('body_shivering', models.BooleanField(default=False, help_text='Experienced body shivering/tremors today?')),
                ('shivering_intensity', models.PositiveSmallIntegerField(blank=True, help_text='If yes, intensity: 1 (mild) to 10 (severe)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, help_text='Any additional thoughts or symptoms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Data Entry',
                'verbose_name_plural': 'Health Data Entries',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
